spring:
  application:
  name: service-registry

eureka:
  client:
    fetch-registry: false
    register-whit-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka

server:
  port: 8080
